### ISSUE TITLE
Can't handle large regions that cross the largest Geofabrik extract borders

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/OSM-realtime-update#2]

**Comment by sedot42** [comment]
Tasks whose geometry extends beyond the borders of Geofabrik largest extracts cannot be handled since we'd need a global file for this.

Example coverage for the Gulf of Mexico, spans North and Central America Geofabrik extracts:
`[ -88.712, 28.881 ] [ -95.831, 27.643 ] [ -96.622, 21.410 ] [ -83.878, 17.097 ] [ -88.712, 28.881 ]`

**Comment by sedot42** [comment]
This needs major changes, basically a world file or another extract source. So far there is no real world demand for this, so closing until real demand occurs...
